SELECT 
    ii2.ITEM_ID,
    ii2.ITEM_NAME,
    ii2.RARITY
FROM ITEM_INFO ii
JOIN ITEM_TREE it ON ii.ITEM_ID = it.PARENT_ITEM_ID
JOIN ITEM_INFO ii2 ON it.ITEM_ID = ii2.ITEM_ID
WHERE 
    CASE 
        WHEN ii.RARITY = 'RARE' THEN 1
        ELSE 0
    END = 1
ORDER BY ii2.ITEM_ID DESC;
